#!/usr/bin/env python
# -*- coding: utf-8 -*-

########################################################################
# finance_dashboard/formatting.py: Value conversion and display helpers
#
#  Description:
#  Turn the raw strings that data.py reads out of a CSV field into the
#  numbers a rule compares and the text a template prints. Every value
#  shown on a page passes through one of these functions, and they are the
#  only place where a field stops being a string.
#
#  Nothing here raises. The fields arrive from files generated by a
#  separate batch job, and the leading rows of ti_CODE.csv are empty by
#  construction: an indicator with a 25-day window has no value for the
#  first 24 days. A conversion that failed with an exception would turn
#  those ordinary gaps into an error page, so an empty, non-numeric, NaN
#  or infinite field converts to zero and renders as such. That tolerance
#  is inherited from the Ruby implementation this replaced, and it is
#  relied upon by indicators.py, whose emphasis rules receive a float and
#  are written on the assumption that they always do.
#
#  The cost of that choice is recorded rather than hidden: a missing value
#  and a genuine zero are indistinguishable downstream. Both render as
#  0.00, and a rule with a lower band will mark a leading empty cell the
#  same way it marks a real zero.
#
#  This module reads no file, holds no state and imports nothing from the
#  rest of the package, so it is the one part that can be reasoned about
#  and tested a value at a time.
#
#  Author: id774 (More info: https://id774.net)
#  Source Code: https://github.com/id774/finance-dashboard
#  License: The GPL version 3, or LGPL version 3 (Dual License).
#  Contact: idnanashi@gmail.com
#
#  Requirements:
#  - Python Version: 3.9 or later
#  - Standard library only
#
#  Version History:
#  v1.0 2026-07-25
#       Initial release.
#
########################################################################

import math
from typing import Any


def to_float(value: Any) -> float:
    """Convert a field to float, returning 0.0 when it is not a finite number."""
    if value is None:
        return 0.0
    try:
        number = float(str(value).strip().replace(",", ""))
    except ValueError:
        return 0.0
    if math.isnan(number) or math.isinf(number):
        return 0.0
    return number


def to_int(value: Any) -> int:
    """Convert a field to int by truncating toward zero."""
    return int(to_float(value))


def number_with_delimiter(value: Any) -> str:
    """Insert thousands separators into an integer value."""
    return "{:,}".format(to_int(value))


def round2(value: Any) -> str:
    """Format a field as a number rounded to two decimal places."""
    return "{:.2f}".format(to_float(value))


def percent(value: Any) -> str:
    """Append a percent sign to a raw ratio field."""
    return "{}%".format(str(value).strip())
